version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.13.1
      - image: circleci/postgres:10.4
    environment:
      - DATABASE_URL: "postgres://localhost:5432/restaurant"
    steps:
      - checkout
      - run: npm install
      - run: npm test